import React from 'react';
export const detectionDetails = () => <div>detection distinct</div>;
export const detection_detail_0 = (p:any)=> <div>detection 0 change detection</div>;
export const detection_detail_1 = (p:any)=> <div>detection 1 crop health</div>;
export const detection_detail_2 = (p:any)=> <div>detection 2 alerts</div>;
export const detection_detail_3 = (p:any)=> <div>detection 3 anomalies</div>;
export const detection_detail_4 = (p:any)=> <div>detection 4 change detection</div>;
export const detection_detail_5 = (p:any)=> <div>detection 5 crop health</div>;
export const detection_detail_6 = (p:any)=> <div>detection 6 alerts</div>;
export const detection_detail_7 = (p:any)=> <div>detection 7 anomalies</div>;
export const detection_detail_8 = (p:any)=> <div>detection 8 change detection</div>;
export const detection_detail_9 = (p:any)=> <div>detection 9 crop health</div>;
export const detection_detail_10 = (p:any)=> <div>detection 10 alerts</div>;
export const detection_detail_11 = (p:any)=> <div>detection 11 anomalies</div>;
export const detection_detail_12 = (p:any)=> <div>detection 12 change detection</div>;
export const detection_detail_13 = (p:any)=> <div>detection 13 crop health</div>;
export const detection_detail_14 = (p:any)=> <div>detection 14 alerts</div>;
export const detection_detail_15 = (p:any)=> <div>detection 15 anomalies</div>;
export const detection_detail_16 = (p:any)=> <div>detection 16 change detection</div>;
export const detection_detail_17 = (p:any)=> <div>detection 17 crop health</div>;
export const detection_detail_18 = (p:any)=> <div>detection 18 alerts</div>;
export const detection_detail_19 = (p:any)=> <div>detection 19 anomalies</div>;