import React from 'react';
export const alertsDetails = () => <div>alerts distinct</div>;
export const alerts_detail_0 = (p:any)=> <div>alerts 0 irrigation</div>;
export const alerts_detail_1 = (p:any)=> <div>alerts 1 pest</div>;
export const alerts_detail_2 = (p:any)=> <div>alerts 2 nutrient</div>;
export const alerts_detail_3 = (p:any)=> <div>alerts 3 per zone</div>;
export const alerts_detail_4 = (p:any)=> <div>alerts 4 irrigation</div>;
export const alerts_detail_5 = (p:any)=> <div>alerts 5 pest</div>;
export const alerts_detail_6 = (p:any)=> <div>alerts 6 nutrient</div>;
export const alerts_detail_7 = (p:any)=> <div>alerts 7 per zone</div>;
export const alerts_detail_8 = (p:any)=> <div>alerts 8 irrigation</div>;
export const alerts_detail_9 = (p:any)=> <div>alerts 9 pest</div>;
export const alerts_detail_10 = (p:any)=> <div>alerts 10 nutrient</div>;
export const alerts_detail_11 = (p:any)=> <div>alerts 11 per zone</div>;
export const alerts_detail_12 = (p:any)=> <div>alerts 12 irrigation</div>;
export const alerts_detail_13 = (p:any)=> <div>alerts 13 pest</div>;
export const alerts_detail_14 = (p:any)=> <div>alerts 14 nutrient</div>;
export const alerts_detail_15 = (p:any)=> <div>alerts 15 per zone</div>;
export const alerts_detail_16 = (p:any)=> <div>alerts 16 irrigation</div>;
export const alerts_detail_17 = (p:any)=> <div>alerts 17 pest</div>;
export const alerts_detail_18 = (p:any)=> <div>alerts 18 nutrient</div>;
export const alerts_detail_19 = (p:any)=> <div>alerts 19 per zone</div>;