import React from 'react';
export const analyticsDetails = () => <div>analytics distinct</div>;
export const analytics_detail_0 = (p:any)=> <div>analytics 0 NDVI trend</div>;
export const analytics_detail_1 = (p:any)=> <div>analytics 1 health</div>;
export const analytics_detail_2 = (p:any)=> <div>analytics 2 time-series</div>;
export const analytics_detail_3 = (p:any)=> <div>analytics 3 comparison</div>;
export const analytics_detail_4 = (p:any)=> <div>analytics 4 NDVI trend</div>;
export const analytics_detail_5 = (p:any)=> <div>analytics 5 health</div>;
export const analytics_detail_6 = (p:any)=> <div>analytics 6 time-series</div>;
export const analytics_detail_7 = (p:any)=> <div>analytics 7 comparison</div>;
export const analytics_detail_8 = (p:any)=> <div>analytics 8 NDVI trend</div>;
export const analytics_detail_9 = (p:any)=> <div>analytics 9 health</div>;
export const analytics_detail_10 = (p:any)=> <div>analytics 10 time-series</div>;
export const analytics_detail_11 = (p:any)=> <div>analytics 11 comparison</div>;
export const analytics_detail_12 = (p:any)=> <div>analytics 12 NDVI trend</div>;
export const analytics_detail_13 = (p:any)=> <div>analytics 13 health</div>;
export const analytics_detail_14 = (p:any)=> <div>analytics 14 time-series</div>;
export const analytics_detail_15 = (p:any)=> <div>analytics 15 comparison</div>;
export const analytics_detail_16 = (p:any)=> <div>analytics 16 NDVI trend</div>;
export const analytics_detail_17 = (p:any)=> <div>analytics 17 health</div>;
export const analytics_detail_18 = (p:any)=> <div>analytics 18 time-series</div>;
export const analytics_detail_19 = (p:any)=> <div>analytics 19 comparison</div>;