import React from 'react';
export const frontendDetails = () => <div>frontend distinct</div>;
export const frontend_detail_0 = (p:any)=> <div>frontend 0 map</div>;
export const frontend_detail_1 = (p:any)=> <div>frontend 1 field view</div>;
export const frontend_detail_2 = (p:any)=> <div>frontend 2 NDVI overlay</div>;
export const frontend_detail_3 = (p:any)=> <div>frontend 3 map</div>;
export const frontend_detail_4 = (p:any)=> <div>frontend 4 field view</div>;
export const frontend_detail_5 = (p:any)=> <div>frontend 5 NDVI overlay</div>;
export const frontend_detail_6 = (p:any)=> <div>frontend 6 map</div>;
export const frontend_detail_7 = (p:any)=> <div>frontend 7 field view</div>;
export const frontend_detail_8 = (p:any)=> <div>frontend 8 NDVI overlay</div>;
export const frontend_detail_9 = (p:any)=> <div>frontend 9 map</div>;
export const frontend_detail_10 = (p:any)=> <div>frontend 10 field view</div>;
export const frontend_detail_11 = (p:any)=> <div>frontend 11 NDVI overlay</div>;
export const frontend_detail_12 = (p:any)=> <div>frontend 12 map</div>;
export const frontend_detail_13 = (p:any)=> <div>frontend 13 field view</div>;
export const frontend_detail_14 = (p:any)=> <div>frontend 14 NDVI overlay</div>;
export const frontend_detail_15 = (p:any)=> <div>frontend 15 map</div>;
export const frontend_detail_16 = (p:any)=> <div>frontend 16 field view</div>;
export const frontend_detail_17 = (p:any)=> <div>frontend 17 NDVI overlay</div>;
export const frontend_detail_18 = (p:any)=> <div>frontend 18 map</div>;
export const frontend_detail_19 = (p:any)=> <div>frontend 19 field view</div>;