import React from 'react';
export const geospatialDetails = () => <div>geospatial distinct</div>;
export const geospatial_detail_0 = (p:any)=> <div>geospatial 0 GIS</div>;
export const geospatial_detail_1 = (p:any)=> <div>geospatial 1 field zones</div>;
export const geospatial_detail_2 = (p:any)=> <div>geospatial 2 boundaries</div>;
export const geospatial_detail_3 = (p:any)=> <div>geospatial 3 GPS</div>;
export const geospatial_detail_4 = (p:any)=> <div>geospatial 4 GIS</div>;
export const geospatial_detail_5 = (p:any)=> <div>geospatial 5 field zones</div>;
export const geospatial_detail_6 = (p:any)=> <div>geospatial 6 boundaries</div>;
export const geospatial_detail_7 = (p:any)=> <div>geospatial 7 GPS</div>;
export const geospatial_detail_8 = (p:any)=> <div>geospatial 8 GIS</div>;
export const geospatial_detail_9 = (p:any)=> <div>geospatial 9 field zones</div>;
export const geospatial_detail_10 = (p:any)=> <div>geospatial 10 boundaries</div>;
export const geospatial_detail_11 = (p:any)=> <div>geospatial 11 GPS</div>;
export const geospatial_detail_12 = (p:any)=> <div>geospatial 12 GIS</div>;
export const geospatial_detail_13 = (p:any)=> <div>geospatial 13 field zones</div>;
export const geospatial_detail_14 = (p:any)=> <div>geospatial 14 boundaries</div>;
export const geospatial_detail_15 = (p:any)=> <div>geospatial 15 GPS</div>;
export const geospatial_detail_16 = (p:any)=> <div>geospatial 16 GIS</div>;
export const geospatial_detail_17 = (p:any)=> <div>geospatial 17 field zones</div>;
export const geospatial_detail_18 = (p:any)=> <div>geospatial 18 boundaries</div>;
export const geospatial_detail_19 = (p:any)=> <div>geospatial 19 GPS</div>;