import React from 'react';
export const fieldsDetails = () => <div>fields distinct</div>;
export const fields_detail_0 = (p:any)=> <div>fields 0 field management</div>;
export const fields_detail_1 = (p:any)=> <div>fields 1 zones</div>;
export const fields_detail_2 = (p:any)=> <div>fields 2 prescription</div>;
export const fields_detail_3 = (p:any)=> <div>fields 3 yield</div>;
export const fields_detail_4 = (p:any)=> <div>fields 4 field management</div>;
export const fields_detail_5 = (p:any)=> <div>fields 5 zones</div>;
export const fields_detail_6 = (p:any)=> <div>fields 6 prescription</div>;
export const fields_detail_7 = (p:any)=> <div>fields 7 yield</div>;
export const fields_detail_8 = (p:any)=> <div>fields 8 field management</div>;
export const fields_detail_9 = (p:any)=> <div>fields 9 zones</div>;
export const fields_detail_10 = (p:any)=> <div>fields 10 prescription</div>;
export const fields_detail_11 = (p:any)=> <div>fields 11 yield</div>;
export const fields_detail_12 = (p:any)=> <div>fields 12 field management</div>;
export const fields_detail_13 = (p:any)=> <div>fields 13 zones</div>;
export const fields_detail_14 = (p:any)=> <div>fields 14 prescription</div>;
export const fields_detail_15 = (p:any)=> <div>fields 15 yield</div>;
export const fields_detail_16 = (p:any)=> <div>fields 16 field management</div>;
export const fields_detail_17 = (p:any)=> <div>fields 17 zones</div>;
export const fields_detail_18 = (p:any)=> <div>fields 18 prescription</div>;
export const fields_detail_19 = (p:any)=> <div>fields 19 yield</div>;